# Generated by Django 3.2.9 on 2021-11-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_account_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='balance',
        ),
    ]
