# Generated by Django 3.2.9 on 2021-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='jira_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'просо в миске'), ('not_done', 'птичка в клетке')], default='not_done', max_length=10),
        ),
    ]
