# Generated by Django 3.2.9 on 2021-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auditlog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'просо в миске'), ('not_done', 'птичка в клетке')], default='not_done', max_length=10),
        ),
    ]
