# Generated by Django 3.2.9 on 2021-11-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
